Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,6 +15,8 @@ jobs:
       run : |
         make minikube-linux-amd64
         make e2e-linux-amd64
+        make minikube-windows-amd64.exe
+        make e2e-windows-amd64.exe
         cp -r test/integration/testdata ./out
         whoami
         echo github ref $GITHUB_REF
@@ -369,11 +371,74 @@ jobs:
           echo "--------------------------------------------"
           numberOfFailures=$(echo $STAT | jq '.NumberOfFail')
           if [ "$numberOfFailures" -gt 0 ];then echo "*** $numberOfFailures Failed ***";exit 2;fi
+  docker_Windows_NT:
+    needs: [build_minikube]
+    env:
+      TIME_ELAPSED: time
+      JOB_NAME: "Docker_Windows_NT"
+      COMMIT_STATUS: ""
+    runs-on: windows-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Install gopogh
+      run: |
+        cd /tmp
+        GO111MODULE="on" go get github.com/medyagh/gopogh@v0.0.17 || true
+        cd -
+      shell: bash
+    - name: Download binaries
+      uses: actions/download-artifact@v1
+      with:
+        name: minikube_binaries
+    - name: run integration test
+      continue-on-error: true
+      run: |
+        set +euo pipefail
+        cd minikube_binaries
+        mkdir -p report
+        mkdir -p testhome
+        chmod a+x e2e-*
+        chmod a+x minikube-*
+        START_TIME=$(date -u +%s)
+        KUBECONFIG=$(pwd)/testhome/kubeconfig MINIKUBE_HOME=$(pwd)/testhome out/e2e-windows-amd64.exe --expected-default-driver=hyperv -minikube-start-args=--vm-driver=hyperv -binary=out/minikube-windows-amd64.exe -test.v -test.timeout=65m 2>&1 | tee ./report/testout.txt
+        END_TIME=$(date -u +%s)
+        TIME_ELAPSED=$(($END_TIME-$START_TIME)) 
+        min=$((${TIME_ELAPSED}/60))
+        sec=$((${TIME_ELAPSED}%60))
+        TIME_ELAPSED="${min} min $sec seconds"
+        echo ::set-env name=TIME_ELAPSED::${TIME_ELAPSED}
+      shell: bash
+    - name: Generate html report
+      run: |
+        cd minikube_binaries
+        export PATH=${PATH}:`go env GOPATH`/bin
+        go tool test2json -t < ./report/testout.txt > ./report/testout.json || true
+        STAT=$(gopogh -in ./report/testout.json -out ./report/testout.html -name " $GITHUB_REF" -repo "${JOB_NAME} ${GITHUB_REF} ${GITHUB_REPOSITORY}"  -details "${GITHUB_SHA}")  || true
+        echo status: ${STAT}
+        FailNum=$(echo $STAT | jq '.NumberOfFail')
+        TestsNum=$(echo $STAT | jq '.NumberOfTests')       
+        GOPOGH_RESULT="${JOB_NAME} : completed with ${FailNum} / ${TestsNum} failures in ${TIME_ELAPSED}"
+        echo ::set-env name=GOPOGH_RESULT::${GOPOGH_RESULT}
+        echo ::set-env name=STAT::${STAT}
+      shell: bash
+    - name: The End Result
+      run: |
+        echo ${GOPOGH_RESULT}
+        echo "--------------------------------------------"
+        echo $STAT | jq '.FailedTests' || true
+        echo "--------------------------------------------"
+        numberOfFailures=$(echo $STAT | jq '.NumberOfFail')
+        if [ "$numberOfFailures" -gt 0 ];then echo "*** $numberOfFailures Failed ***";exit 2;fi
+      shell: bash
+    - uses: actions/upload-artifact@v1
+      with:
+        name: docker_Windows_NT
+        path: minikube_binaries/report
   # After all 4 integration tests finished 
   # collect all the reports and upload
   upload_all_reports:
     if: always()
-    needs: [docker_ubuntu_16_04,docker_ubuntu_18_04,none_ubuntu16_04,none_ubuntu18_04,podman_ubuntu_18_04]
+    needs: [docker_ubuntu_16_04,docker_ubuntu_18_04,none_ubuntu16_04,none_ubuntu18_04,podman_ubuntu_18_04, docker_Windows_NT]
     runs-on: ubuntu-18.04
     steps:
     - name: download results docker_ubuntu_16_04
@@ -421,6 +486,16 @@ jobs:
       run: |
         mkdir -p all_reports
         cp -r podman_ubuntu_18_04 ./all_reports/
+    
+    - name: download results docker_Windows_NT
+      uses: actions/download-artifact@v1
+      with:
+        name: docker_Windows_NT
+    - name: cp to all_report
+      shell: bash
+      run: |
+        mkdir -p all_reports
+        cp -r docker_Windows_NT ./all_reports/
     - uses: actions/upload-artifact@v1
       with:
         name: all_reports
